
platform :ios do

  desc "Runs all the tests"
  lane :test do

    scan(
      scheme: "iOS Client",
      output_directory: ".ci/xcodebuild-data/",
      xcargs: "-derivedDataPath .ci/xcodebuild-data/"
    )
    
  end
end

platform :mac do
  
  desc "Runs all the tests"
  lane :test do

    scan(
      scheme: "OS X Client",
      output_directory: ".ci/xcodebuild-data/",
      xcargs: "-derivedDataPath .ci/xcodebuild-data/"
    )
        
  end
end
